// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZpsW-SR-7PHxDp-oHgjXVEFnT0bkJOyo',
    appId: '1:174167442960:web:b7ff7d8f1310e71c2f2c95',
    messagingSenderId: '174167442960',
    projectId: 'culture-p',
    authDomain: 'culture-p.firebaseapp.com',
    databaseURL: 'https://culture-p-default-rtdb.firebaseio.com',
    storageBucket: 'culture-p.appspot.com',
    measurementId: 'G-1RH4JLVWRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHTakeXo6w5LCmwH-KdaqxskI8uWmIbc',
    appId: '1:174167442960:android:8971f3c6550c59282f2c95',
    messagingSenderId: '174167442960',
    projectId: 'culture-p',
    databaseURL: 'https://culture-p-default-rtdb.firebaseio.com',
    storageBucket: 'culture-p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuhjdm072Ap3MGTvamrel1N7eHETYJJ38',
    appId: '1:174167442960:ios:6a77bcaa31df1e8f2f2c95',
    messagingSenderId: '174167442960',
    projectId: 'culture-p',
    databaseURL: 'https://culture-p-default-rtdb.firebaseio.com',
    storageBucket: 'culture-p.appspot.com',
    iosBundleId: 'com.example.culturePot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuhjdm072Ap3MGTvamrel1N7eHETYJJ38',
    appId: '1:174167442960:ios:0ceb22ce45d014042f2c95',
    messagingSenderId: '174167442960',
    projectId: 'culture-p',
    databaseURL: 'https://culture-p-default-rtdb.firebaseio.com',
    storageBucket: 'culture-p.appspot.com',
    iosBundleId: 'com.example.culturePot.RunnerTests',
  );
}
